default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-42188

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-42188
  pool: 10

production:
  <<: *default
  adapter: mysql2
  database: furima_42188_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock